name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}] # Daily
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: LuisTschurtschenthaler
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          plugin_languages: yes
          plugin_languages_ignored: css, html
          plugin_languages_details: bytes-size, percentage
          plugin_lines: yes
